[package]
name = "deny_rust"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "deny_rust"
crate-type = ["cdylib"]

[dependencies]
aho-corasick = "1.1.4"
pyo3 = "0.28.0"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"