[licenses]
unused-allowed-license = "warn"
confidence-threshold = 0.95
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "BSD-2-Clause",
]
