name: Rust Tools CI/CD

on:
  push:
    branches: [main, develop]
    paths: ["./**", ".github/workflows/rust-plugin.yml"]
  pull_request:
    branches: [main]
    paths: ["./**"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy, llvm-tools-preview

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Format & Check & Clippy
        run: |
          cargo fmt --check
          cargo check
          cargo clippy -- -D warnings

      - name: Run tests & Coverage
        uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo llvm-cov --fail-under-lines 80 --summary-only >> $GITHUB_STEP_SUMMARY

  licenses-audit:
    name: Licenses Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-deny
        uses: taiki-e/install-action@cargo-deny
      - run: cargo deny check licenses