name: Rust Tools CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy, llvm-tools-preview

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Format --check
        run: cargo fmt --check

      - name: Cargo check
        run: cargo check

      - name: Clippy
        run: cargo clippy --all-targets -- -W clippy::pedantic -D warnings

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate Coverage Summary
        run: |
          cargo llvm-cov --summary-only > /tmp/cov-summary.txt
          echo "### Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat /tmp/cov-summary.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Enforce Coverage Threshold
        run: cargo llvm-cov report --fail-under-lines 90

  licenses-audit:
    name: Licenses Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-deny
        uses: taiki-e/install-action@cargo-deny
      - run: cargo deny check licenses